### ISSUE TITLE
Crashing on Inject

### ISSUE THREAD

**Issue by DemonLoverHvH** [roddyuwu/eclipse#2]
as the title says it crashes when injecting, my guess would be it crashes during hooking but i'll try and find it and make a pull request if I do

**Comment by unencouraged** [comment]
step 1 attach debugger
step 2 read callstack
step 3 fix problem
step 4 done

**Comment by unencouraged** [comment]
step 1 start csgo
step 2 attach debugger
step 3 inject cheat
step 4 crash
step 5 fix
